version: 0.2
phase:
  installl:
      runtime-versions:
        nodejs: 18
      commands:
        - npm install
        - npm install typescript -g
        - npm install typescript --save-dev
        - tsc --init
artifacts:
  files:
    -"**/*"