version: 0.2
phase:
  install:
      runtime-versions:
        nodejs: 18
      commands:
        - npm install -g typescript
        - npm install
  build:
      commands:
        - npm run build
artifacts:
  files:
    -"**/*"