AWSTemplateFormatVersion: '2010-09-09'
Description: 'CloudFormation template for PhotoComp DynamoDB table'

Parameters:
    ApplicationName:
        Type: String
        Default: PhotoComp
        Description: Name of the application

    Environment:
        Type: String
        Default: Dev
        AllowedValues:
            - Dev
            - Test
            - Prod
        Description: Deployment environment

Resources:
    PhotoCompTable:
        Type: AWS::DynamoDB::Table
        Properties:
            # Use dynamic table name with environment to make it unique
            TableName: !Sub '${ApplicationName}-${Environment}-Table'
            BillingMode: PAY_PER_REQUEST
            AttributeDefinitions:
                - AttributeName: PK
                  AttributeType: S
                - AttributeName: SK
                  AttributeType: S
                - AttributeName: GSI1PK
                  AttributeType: S
                - AttributeName: GSI1SK
                  AttributeType: S
                - AttributeName: GSI2PK
                  AttributeType: S
                - AttributeName: GSI2SK
                  AttributeType: S
            KeySchema:
                - AttributeName: PK
                  KeyType: HASH
                - AttributeName: SK
                  KeyType: RANGE
            GlobalSecondaryIndexes:
                - IndexName: GSI1PK-GSI1SK-INDEX
                  KeySchema:
                      - AttributeName: GSI1PK
                        KeyType: HASH
                      - AttributeName: GSI1SK
                        KeyType: RANGE
                  Projection:
                      ProjectionType: ALL
                - IndexName: GSI2PK-GSI2SK-INDEX # Added new GSI for photo queries by event
                  KeySchema:
                      - AttributeName: GSI2PK
                        KeyType: HASH
                      - AttributeName: GSI2SK
                        KeyType: RANGE
                  Projection:
                      ProjectionType: ALL
            PointInTimeRecoverySpecification:
                PointInTimeRecoveryEnabled: false
            SSESpecification:
                SSEEnabled: true
            Tags:
                - Key: Application
                  Value: !Ref ApplicationName
                - Key: Environment
                  Value: !Ref Environment
