version = 0.1
[default.deploy.parameters]
stack_name = "photocomp-node-sam"
resolve_s3 = true
s3_prefix = "photocomp-node-sam"
region = "us-east-1"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
parameter_overrides = "ApplicationName=\"PhotoComp\" Environment=\"Prod\""
image_repositories = ["PhotoCompFunction=533267362219.dkr.ecr.us-east-1.amazonaws.com/photocompnodesam4c7438db/photocompfunctionaeb8ae90repo"]
